spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/honterview?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${HOST_URI}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - account_email
              - profile_nickname
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GIT_CLIENT_ID}
            client-secret: ${GIT_CLIENT_SECRET}
            redirect-uri: ${HOST_URI}/login/oauth2/code/github

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiry-seconds: 1800 #30 min
  refresh-expiry-seconds: 604800 #7 day

openai:
  secret-key: ${OPEN_AI_SECRET_KEY}
  model: ${GPT_MODEL}
  end-point: https://api.openai.com/v1/chat/completions

logging:
  level:
    org.hibernate.SQL: INFO
